### ISSUE TITLE
Has the error

### ISSUE THREAD

**Issue by greister** [ali--/intellij-scala-docker#1]
Setting up gcc-5 (5.4.0-6ubuntu1~16.04.4) ...                                       
Setting up gcc (4:5.3.1-1ubuntu1) ...                                               
Setting up libc-dev-bin (2.23-0ubuntu7) ...                                         
Setting up linux-libc-dev:amd64 (4.4.0-78.99) ...                                   
Setting up libc6-dev:amd64 (2.23-0ubuntu7) ...                                      
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-2ubuntu4.1) ...                           
Setting up libssl-dev:amd64 (1.0.2g-1ubuntu4.6) ...                                 
Setting up make (4.1-6) ...                                                         
Processing triggers for libc-bin (2.23-0ubuntu7) ...                                
                                                                                    
gzip: stdin: not in gzip format                                                     
tar: Child returned status 1                                                        
tar: Error is not recoverable: exiting now                                          
The command '/bin/sh -c apt-get update && apt-get install ca-certificates curl      
   gcc libc6-dev libssl-dev make         -y --no-install-recommends &&  mkdir -p /us
r/lib/jvm &&    curl --silent --location --retry 3 --cacert /etc/ssl/certs/GeoTrust_
Global_CA.pem   --header "Cookie: oraclelicense=accept-securebackup-cookie;"    http
://download.oracle.com/otn-pub/java/jdk/"${JAVA_VERSION}"u"${JAVA_UPDATE}"-b"${JAVA_
BUILD}"/server-jre-"${JAVA_VERSION}"u"${JAVA_UPDATE}"-linux-x64.tar.gz  | tar xz -C 
/usr/lib/jvm &&     apt-get remove --purge --auto-remove -y             gcc         
    libc6-dev             libssl-dev             make &&        apt-get autoclean &&
 apt-get --purge -y autoremove &&       rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/
*' returned a non-zero code: 2

**Comment by ali1rathore** [comment]
I've modified the Dockerfile to use openjdk instead of oracle.
Thanks for filing this issue :)
